// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADcL0or5vw2LMeEtqxL78yLic1eNZR2Wg',
    appId: '1:957387008818:web:4cb01d9bdb59cfaa46452b',
    messagingSenderId: '957387008818',
    projectId: 'musicplayer-68224',
    authDomain: 'musicplayer-68224.firebaseapp.com',
    storageBucket: 'musicplayer-68224.appspot.com',
    measurementId: 'G-VV3JXZ37BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQC6R6fSL-W1R6EhaPJb6SRJogkYZC-so',
    appId: '1:957387008818:android:de829896aeabbfb046452b',
    messagingSenderId: '957387008818',
    projectId: 'musicplayer-68224',
    storageBucket: 'musicplayer-68224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNciT8Ri4saZiXrH2y_FQEFtR8Y3AeYo',
    appId: '1:957387008818:ios:c9f8e3159c39217646452b',
    messagingSenderId: '957387008818',
    projectId: 'musicplayer-68224',
    storageBucket: 'musicplayer-68224.appspot.com',
    iosBundleId: 'com.example.musicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyNciT8Ri4saZiXrH2y_FQEFtR8Y3AeYo',
    appId: '1:957387008818:ios:e48bcbee14b70d2446452b',
    messagingSenderId: '957387008818',
    projectId: 'musicplayer-68224',
    storageBucket: 'musicplayer-68224.appspot.com',
    iosBundleId: 'com.example.musicPlayer.RunnerTests',
  );
}
